FROM python:3.9

WORKDIR /app

ADD requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ADD connect_ais.py .

ENV KAFKA_SERVER=host.docker.internal:9092

CMD ["python", "./connect_ais.py"]
