version: '3.9'

services:
  connect_ais:
    image: mileristo/stream_ais:v2 
    hostname: WebSocketsConnection
    container_name: WebSocketsConnection
    environment:
      - KAFKA_SERVER=host.docker.internal:29092
      - KAFKA_TOPIC=ais_data
      - AIS_STREAM_URL=wss://stream.aisstream.io/v0/stream
      - API_KEY=e66dea5edc96977c45bd4ddba1e1b34acf718a04
      - LAT_BOTTOM_LEFT=-90
      - LON_BOTTOM_LEFT=-180
      - LAT_TOP_RIGHT=90
      - LON_TOP_RIGHT=180
